# webhook admission controller
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kubernetes-cronhpa-service
#  namespace: kube-system
#  labels:
#    app: kubernetes-cronhpa-controller
#    controller-tools.k8s.io: "1.0"
#spec:
#  selector:
#    app: kubernetes-cronhpa-controller
#    controller-tools.k8s.io: "1.0"
#  ports:
#  - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cronhpa-controller
  namespace: kube-system
  labels:
    app: kubernetes-cronhpa-controller
    controller-tools.k8s.io: "2.0"
spec:
  selector:
    matchLabels:
      app: kubernetes-cronhpa-controller
      controller-tools.k8s.io: "2.0"
  template:
    metadata:
      labels:
        app: kubernetes-cronhpa-controller
        controller-tools.k8s.io: "2.0"
    spec:
      containers:
      - command:
        - /root/kubernetes-cronhpa-controller
        image: registry.cn-beijing.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.3.0-f9010e90-aliyun
        imagePullPolicy: Always
        name: kubernetes-cronhpa-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccount: kubernetes-cronhpa-controller
